#!/usr/bin/env python3
"""naming_map.py — FINAL slug mapping for 73 finance skills.

Source of truth: docs/research/2026-04-22-skill-naming-FINAL.md
"""

FINAL_SLUG_MAP: dict[str, str] = {
    # 2026-04-23 renamed: original slug collided with hexavi8's skill
    "finance-bp-004--daily_stock_analysis": "daily-stock-analyzer",
    "finance-bp-009--zvt": "a-stock-quant-lab",
    "finance-bp-020--gs-quant": "gs-quant-pricing",
    "finance-bp-050--skorecard": "credit-scorecard",
    "finance-bp-060--AMLSim": "aml-data-generator",
    "finance-bp-061--FinRL": "finrl-rl-trading",
    "finance-bp-062--ifrs9": "ifrs9-loss-engine",
    "finance-bp-063--chainladder-python": "insurance-loss-reserving",
    "finance-bp-064--insurance_python": "insurance-actuarial-python",
    "finance-bp-065--pyliferisk": "life-insurance-math",
    "finance-bp-066--wealthbot": "robo-advisor-python",
    "finance-bp-067--firesale_stresstest": "firesale-stress-test",
    "finance-bp-068--xalpha": "xalpha-fund-tool",
    "finance-bp-069--tqsdk-python": "tqsdk-futures-api",
    "finance-bp-070--edgartools": "sec-edgar-tools",
    "finance-bp-071--opensanctions": "opensanctions-watchlist",
    "finance-bp-072--lending": "p2p-lending-data",
    "finance-bp-073--ledger": "ledger-plaintext-accounting",
    "finance-bp-074--FinRobot": "finrobot-multi-agent",
    "finance-bp-076--AbsBox": "abs-cashflow-modeling",
    "finance-bp-077--Open_Source_Economic_Model": "macro-economic-model",
    "finance-bp-078--fava_investor": "fava-beancount-viewer",
    "finance-bp-079--akshare": "akshare-financial-data",
    "finance-bp-080--FinDKG": "finance-kg-embedding",
    "finance-bp-081--vnpy": "vnpy-futures-trading",
    "finance-bp-082--stock-screener": "stock-pattern-screener",
    "finance-bp-083--Economic-Dashboard": "economic-dashboard",
    "finance-bp-084--eastmoney": "eastmoney-api",
    "finance-bp-085--freqtrade": "freqtrade-crypto-bot",
    "finance-bp-086--backtrader": "backtrader-event-driven",
    "finance-bp-087--qlib": "qlib-ai-quant",
    "finance-bp-088--zipline-reloaded": "zipline-daily-backtest",
    "finance-bp-089--rqalpha": "rqalpha-cn-backtest",
    "finance-bp-090--QUANTAXIS": "quantaxis-data-platform",
    "finance-bp-091--czsc": "czsc-chan-theory",
    "finance-bp-092--vectorbt": "vectorbt-vectorized",
    "finance-bp-093--PyPortfolioOpt": "portfolio-optimization",
    "finance-bp-094--easytrader": "easytrader-cn-broker",
    "finance-bp-095--rotki": "rotki-crypto-tracker",
    "finance-bp-096--hummingbot": "hummingbot-market-maker",
    "finance-bp-097--OpenBB": "openbb-terminal",
    "finance-bp-098--nautilus_trader": "nautilus-algo-trading",
    "finance-bp-099--TradingAgents-CN": "trading-agents-cn",
    "finance-bp-100--LEAN": "lean-cloud-backtest",
    "finance-bp-101--FinancePy": "financepy-derivatives",
    "finance-bp-102--Darts": "darts-forecasting",
    "finance-bp-103--ArcticDB": "arcticdb-timeseries",
    "finance-bp-104--Engine": "reactive-pricing-engine",
    "finance-bp-105--open-climate-investing": "climate-esg-investing",
    "finance-bp-106--pyfolio-reloaded": "pyfolio-performance",
    "finance-bp-107--empyrical-reloaded": "empyrical-risk-metrics",
    "finance-bp-108--finmarketpy": "cuemacro-finmarket",
    "finance-bp-109--ta-lib-python": "talib-technical-analysis",
    "finance-bp-110--cryptofeed": "cryptofeed-ws-feeds",
    "finance-bp-111--ccxt": "ccxt-crypto-api",
    "finance-bp-112--openLGD": "credit-lgd-model",
    "finance-bp-114--edgar-crawler": "edgar-crawler",
    "finance-bp-115--mlfinlab": "advanced-financial-ml",
    "finance-bp-116--FinRL-Meta": "finrl-meta-envs",
    "finance-bp-117--Riskfolio-Lib": "riskfolio-optimization",
    "finance-bp-118--FinanceToolkit": "financial-ratios-toolkit",
    "finance-bp-119--transitionMatrix": "credit-transition-matrix",
    "finance-bp-120--alphalens-reloaded": "alphalens-factor-analysis",
    "finance-bp-121--machine-learning-for-trading": "ml4t-book-notebooks",
    "finance-bp-122--ta-python": "pandas-ta-indicators",
    "finance-bp-123--QuantLib-SWIG": "quantlib-derivatives",
    "finance-bp-124--arch": "arch-garch-volatility",
    "finance-bp-125--bt": "bt-portfolio-backtest",
    "finance-bp-126--lifelines": "lifelines-survival-analysis",
    "finance-bp-127--py_vollib": "py-vollib-options-pricing",
    "finance-bp-128--yfinance": "yfinance-market-data",
    "finance-bp-129--beancount": "beancount-plaintext-ledger",
    "finance-bp-130--tensortrade": "tensortrade-rl-env",
}
