# {workspace}/validate.py
# DO NOT EDIT — crystal contract enforcement for finance-bp-009
# Generated by compile_crystal_skeleton.py v5.0

import sys
import json
import inspect
from pathlib import Path


def enforce_validation(result, output_path: str) -> None:
    failures = []

    # OV-01: MACD parameter lock (SL-08)
    try:
        import zvt.factors.algorithm as _algo
        src = inspect.getsource(_algo.macd)
        if "slow=26" not in src or "fast=12" not in src or "n=9" not in src:
            failures.append("FATAL OV-01: MACD params drifted from (fast=12, slow=26, n=9) — SL-08 violation")
    except Exception:
        pass

    # OV-02: Business-semantic trade count check (not structural non-emptiness)
    if result is None:
        failures.append("FATAL OV-02: result is None — no computation performed")
    elif isinstance(result, dict):
        total_trades = result.get("total_trades", 0)
        zero_ack = result.get("explicit_zero_trade_ack") is True
        if total_trades == 0 and not zero_ack:
            failures.append(
                "FATAL OV-02: Zero trades executed — likely missing pre-fetched data (PC-02) "
                "or over-restrictive filters. Set result['explicit_zero_trade_ack']=True to ack intentional zero-trade."
            )

    # OV-03: annual return physical plausibility
    try:
        if hasattr(result, "get"):
            ar = result.get("annual_return")
            if ar is not None and abs(float(ar)) > 5.0:
                failures.append(f"FATAL OV-03: |annual_return|={float(ar):.2f} > 500% — likely look-ahead bias")
    except Exception:
        pass

    # OV-04: holding change plausibility
    try:
        if hasattr(result, "get"):
            hc = result.get("holding_change_pct")
            if hc is not None and abs(float(hc)) > 1.0:
                failures.append(f"FATAL OV-04: |holding_change_pct|={float(hc):.2f} > 100%")
    except Exception:
        pass

    # OV-05: drawdown plausibility
    try:
        if hasattr(result, "get"):
            dd = result.get("max_drawdown")
            if dd is not None and abs(float(dd)) > 1.0:
                failures.append(f"FATAL OV-05: |max_drawdown|={float(dd):.2f} > 100% — impossible without leverage")
    except Exception:
        pass

    # OV-06: sell-before-buy ordering (SL-01)
    try:
        if hasattr(result, "trade_log") and result.trade_log:
            log = result.trade_log
            for i in range(len(log) - 1):
                if (log[i].action == "sell"
                        and log[i + 1].action == "buy"
                        and log[i].timestamp == log[i + 1].timestamp):
                    # This is correct order (sell then buy same cycle) — OK
                    pass
                elif (log[i].action == "buy"
                        and log[i + 1].action == "sell"
                        and log[i].timestamp == log[i + 1].timestamp):
                    failures.append("FATAL OV-06: buy-before-sell in same cycle — SL-01 violation")
                    break
    except Exception:
        pass

    # === END assertions ===

    if failures:
        Path(f"{output_path}.FAILED.log").write_text("\n".join(failures))
        sys.stderr.write("\n".join(failures) + "\n")
        sys.exit(1)

    # Write result
    if hasattr(result, "to_csv"):
        result.to_csv(output_path, index=False)
    elif isinstance(result, dict):
        Path(output_path).write_text(json.dumps(result, indent=2, default=str))
    elif result is None:
        Path(output_path).write_text("")
    else:
        Path(output_path).write_text(str(result))

    Path(f"{output_path}.validation_passed").touch()


if __name__ == "__main__":
    print("[validate.py] Standalone mode — checking SL parameter integrity...")
    failures = []
    try:
        import zvt.factors.algorithm as _algo
        import inspect
        src = inspect.getsource(_algo.macd)
        if "slow=26" not in src:
            failures.append("SL-08: MACD slow != 26")
        if "fast=12" not in src:
            failures.append("SL-08: MACD fast != 12")
        if "n=9" not in src:
            failures.append("SL-08: MACD n != 9")
    except ImportError:
        print("[validate.py] zvt not installed — cannot verify SL-08")

    if failures:
        for f in failures:
            print(f"  FAIL: {f}")
        sys.exit(1)
    print("[validate.py] ALL GATES PASSED.")
    sys.exit(0)
